FILES:
  - ake.csv
  - kem.csv
  - commitment.csv
  - gake.csv
ALGS:
  - Classic-McEliece-348864
  - Classic-McEliece-348864f
  - Classic-McEliece-460896
  - Classic-McEliece-460896f
  - Classic-McEliece-6688128
  - Classic-McEliece-6688128f
  - Classic-McEliece-6960119
  - Classic-McEliece-6960119f
  - Classic-McEliece-8192128
  - Classic-McEliece-8192128f
  - Kyber512
  - Kyber768
  - Kyber1024
  - NTRU-HPS-2048-509
  - NTRU-HPS-2048-677
  - NTRU-HRSS-701
  - NTRU-HPS-4096-821
  - LightSaber-KEM
  - Saber-KEM
  - FireSaber-KEM
L1:
  - Classic-McEliece-348864
  - Classic-McEliece-348864f
  - Kyber512
  - NTRU-HPS-2048-509
  - LightSaber-KEM
L3:
  - Classic-McEliece-460896
  - Classic-McEliece-460896f
  - Kyber768
  - NTRU-HPS-2048-677
  - NTRU-HRSS-701
  - Saber-KEM
L5:
  - Classic-McEliece-6688128
  - Classic-McEliece-6688128f
  - Classic-McEliece-6960119
  - Classic-McEliece-6960119f
  - Classic-McEliece-8192128
  - Classic-McEliece-8192128f
  - Kyber1024
  - NTRU-HPS-4096-821
  - FireSaber-KEM
FOLDER: "build"
OUTPUT_FOLDER: "results"
